# this is an example of the Crimes API
# as a demonstration of an API spec in YAML
swagger: "2.0"
info:
  title: Crimes API
  description: Identify crime prone areas near you
  version: "1.0.0"
# the domain of the service
  contact:
    name: "Kadupitige Kadupitiya"
    email: jasakadu@iu.edu
  license: 
    name: "Apache"
host: "localhost:8080"
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /cloudmesh/crime_finder/
securityDefinitions:
  basicAuth:
    type: basic
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths:
  /crimes:
    get:
      summary: Crimes
      description: The Crimes endpoint returns information about the crimes previously happened at a given location or nearby locations. The response includes lists of crimes in the proper display order.
      parameters:
        - name: latitude
          in: query
          description: Latitude component of location.
          required: true
          type: number
          format: double
        - name: longitude
          in: query
          description: Longitude component of location.
          required: true
          type: number
          format: double
        - name: radius
          in: query
          description: Radius to search.
          required: true
          type: number
          format: double
      security:
        - basicAuth: []
      tags: 
        - Crimes
      responses:  
        "200":
          description: An array of Crimes
          schema:
            type: array
            items:
              $ref: '#/definitions/Crime'
        default:
          description: Unexpected error while retrieving the crime list
          schema:
            $ref: '#/definitions/Error'

  /crimes/search:
    get:
      summary: Search for a crime
      description: User can search for a perticluar crime with crime_id.
      parameters:
        - name: crime_id
          in: query
          description: Unique identifier representing a specific crime according to chicago police.
          required: true
          type: string
      security:
        - basicAuth: []
      tags: 
        - Crimes
      responses:  
        "200":
          description: Crime Object
          schema:
            type: object
            items:
              $ref: '#/definitions/Crime'
        default:
          description: Unexpected error while retrieving the crime object for the crime_id
          schema:
            $ref: '#/definitions/Error'

  /crimes/filter:
    get:
      summary: crimeList based on primary_type
      description: The crimes/filter endpoint returns information about the crimes previously happened at a given location or nearby locations based on user's GPS coordinates and a primary_type (Example- BATTERY).
      parameters:
        - name: latitude
          in: query
          description: Latitude component of location.
          required: true
          type: number
          format: double
        - name: longitude
          in: query
          description: Longitude component of location.
          required: true
          type: number
          format: double
        - name: primary_type
          in: query
          description: primary_type of a crime.
          required: true
          type: string
        - name: radius
          in: query
          description: Radius to search.
          required: true
          type: number
          format: double
      security:
        - basicAuth: []
      tags: 
        - Crimes
      responses:  
        "200":
          description: An array of Crimes
          schema:
            type: array
            items:
              $ref: '#/definitions/Crime'
        default:
          description: Unexpected error while retrieving the crime list
          schema:
            $ref: '#/definitions/Error'
    
  /crimes/list:
    get:
      summary: Get the basic crime list
      description: User can get metadata list using this API.
      security:
        - basicAuth: []
      tags: 
          - Crimes
      responses:  
        "200":
          description: Crime List Object
          schema:
            type: object
            items:
              $ref: '#/definitions/CrimeList'
        default:
          description: Unexpected error while retrieving the CrimeList object
          schema:
             $ref: '#/definitions/Error'

  /crimes/byday:
    get:
      summary: Get the top x crimes by day
      description: User can get top x crimes by day using this API.
      parameters:
        - name: no_of_types
          in: query
          description: How many top crime categeries are required?
          required: true
          type: integer      
      security:
        - basicAuth: []
      tags: 
          - Crimes
      responses:  
        "200":
          description: Data as a String for plotting
          schema:
            type: string
        default:
          description: Unexpected error while calculating crimes by day
          schema:
             $ref: '#/definitions/Error'

  /crimes/byyear:
    get:
      summary: Get the top x crimes by year
      description: User can get top x crimes by year using this API.
      parameters:
        - name: no_of_types
          in: query
          description: How many top crime categeries are required?
          required: true
          type: integer      
      security:
        - basicAuth: []
      tags: 
          - Crimes
      responses:  
        "200":
          description:  Data as a String for plotting
          schema:
            type: string
        default:
          description: Unexpected error while calculating crimes by day
          schema:
             $ref: '#/definitions/Error'


  /data:
    get:
      summary: returns the folder name and file name of the dataset
      description: The data endpoint returns a data object conataining information about dataset files.
      security:
        - basicAuth: []
      tags: 
        - Data
      responses:  
        "200":
          description: An object of Data
          schema:
            type: object
            items:
              $ref: '#/definitions/Data'
        default:
          description: Unexpected error while retrieving the crime list
          schema:
            $ref: '#/definitions/Error'

  /data/fetch:
    get:
      summary: Fetch data to the server
      description: This data fetch endpoint upload the csv datafiles to the server using predeifned urls
      security:
        - basicAuth: []
      tags: 
        - Data
      responses:  
        "200":
          description: An Object of Response
          schema:
            type: object
            items:
              $ref: '#/definitions/Response'
        default:
          description: Unexpected error while retrieving the crime list
          schema:
            $ref: '#/definitions/Error'

            

definitions:
  Crime:
    type: object
    required: 
      - crime_id
    properties:
      crime_id:
        type: string
        description: Unique identifier representing a specific crime according to chicago police.
      case_number:
        type: string
        description: Case Number.
      date:
        type: string
        description: Date of the crime.
      block:
        type: string
        description: Block Address.
      crime_code:
        type: string
        description: IUCR by chicago police.
      primary_description:
        type: string
        description: Primary Type.
      secondary_description:
        type: string
        description: Description.
      location_cat:
        type: string
        description: Location Description/catogery.
      arrested:
        type: boolean
        description: Arrested.
      domestic:
        type: boolean
        description: Domestic.
      beat_code:
        type: string
        description: Beat Code.
      district_code:
        type: string
        description: District Code.
      ward_code:
        type: string
        description: Ward Code.
      community_area_code:
        type: string
        description: Community Area code.
      fbi_code:
        type: string
        description: FBI Code.
      x_coordinate:
        type: string
        description: X Coordinate.
      y_coordinate:
        type: string
        description: Y Coordinate.
      year:
        type: string
        description: Year of the crime.
      updated_on:
        type: string
        description: Last Updated On.
      latitude:
        type: string
        description: Latitude.
      longitude:
        type: string
        description: Longitude.
      gps_location:
        type: string
        description: GPS Location.

  Data:
    properties:
      base_path:
        type: string
      filename:
        type: string
      filename_short:
        type: string
      url:
        type: string
        
  CrimeList:
    properties:
      primaryType:
        type: string
      index:
        type: integer
        
      primaryType_display:
        type: string

  Response:
    properties:
      status:
        type: boolean
      message:
        type: string
      data:
        type: object


  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
