# coding: utf-8

# flake8: noqa

"""
    Crimes API

    Identify crime prone areas near you  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.crimes_api import CrimesApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.crime import Crime
from swagger_client.models.error import Error
