# coding: utf-8

"""
    Crimes API

    Identify crime prone areas near you  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.crime import Crime  # noqa: E501
from swagger_client.rest import ApiException


class TestCrime(unittest.TestCase):
    """Crime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCrime(self):
        """Test Crime"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.crime.Crime()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
